/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_com_zh_myapplication_utils_JniUtils */

#ifndef _Included_test_com_zh_myapplication_utils_JniUtils
#define _Included_test_com_zh_myapplication_utils_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_com_zh_myapplication_utils_JniUtils
 * Method:    testFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_test_com_zh_myapplication_utils_JniUtils_testFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
